config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get '/home/about' => 'homes#about',as: 'about'

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :index, :update ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


  has_one_attached :image
  belongs_to :user

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  has_many :books, dependent: :destroy
  has_many :posts, dependent: :destroy
  


  has_one_attached :profile_image


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top,:about]
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def create
  @user = current_user
  @book = Book.new(book_params)
  @book.user_id = @user.id
  @books = @user.books

  if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    render :index
  end
 end


 def index
  @user = current_user
  @books = Book.all
  @book = Book.new

 end

  def show
   @user = current_user
   @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  if @book.user_id != current_user.id
    redirect_to books_path, notice: "You are not authorized to edit this book."
  end
  end



  def update

    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to @book, notice: "Book was successfully updated."
   else
    render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


 private

 def book_params
  params.require(:book).permit(:title, :body, :user_id)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end 
  
  def about
   
  end 
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = current_user
    @books = @user.books
    @users = User.all
  end

  def edit
  @user = User.find(params[:id])
  unless @user.id == current_user.id
    redirect_to user_path(current_user)
  end

  end


  def update
   @user = User.find(params[:id])
   if @user.update(user_params)

    redirect_to user_path(@user), notice: "You have updated user successfully."
   else
    render :edit
   end
  end

  private

  def user_params
     params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
  <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
   <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
  </ul>
  <% end %>
  
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
 <div class="form-group">
 <p>Title</p>
 <%= f.text_field :title, class: "form-control" %>
 </div>
 <div class="form-group">
 <p>Opinion</p>
  <%= f.text_area :body, class: "form-control" %>
<br>
 <div class="form-group">
  <%= f.submit 'Update Book', class: "btn btn-success" %>
 </div>
 <%= link_to "Show", book_path(@book) %>
 |
 <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<body>
  <main>
  <div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
   <div class="row">
    <div class="col-md-3">
      <h2 class="mb-0 border-bottom-0">User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
       <% if @user.profile_image.attached? %>
         <%= image_tag(@user.profile_image.variant(resize_to_limit: [100, 100])) %>
           <% else %>
             <%= image_tag 'no_image', size: "100x100" %>
       <% end %>
            </td>
          </tr>
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>

<div class="row">
  <div class="col-12">
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" aria-hidden="true"></i>
    <% end %>
  </div>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control" %>
  <p class="mt-3">Opinion</p>
  <%= f.text_area :body, class: "form-control" %>
  <%= f.submit 'Create Book', class: "btn btn-success mt-3 " %>
<% end %>

</div>


<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <% if book.user.profile_image.attached? %>
          <%= link_to user_path(book.user) do %>
       <%= image_tag(book.user.profile_image.variant(resize_to_limit: [100, 100])) %>
       <% end %>
    <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

    </div>
  </div>
 </main>
</body>

app/views/books/new.html.erb
<body>
  <main>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag(@user.profile_image.variant(resize_to_limit: [100, 100]), class: "rounded-circle") if @user.profile_image.attached? %>
            </td>
          </tr>
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>

<div class="row">
  <div class="col-12">
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" aria-hidden="true"></i>
    <% end %>
  </div>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control" %>
  <p class="mt-3">Opinion</p>
  <%= f.text_area :body, class: "form-control" %>
  <%= f.submit 'Create Book', class: "btn btn-success mt-3 " %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
  </tr>
<% end %>
</tbody>
    
  </table>
     </div>
    </div>
  </div>
 </main>
</body>

app/views/books/show.html.erb
<body>
<main>
<div>
  <%= flash[:notice] %>
  </div>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mb-0 border-bottom-0">User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
       <% if @book.user.profile_image.attached? %>
         <%= link_to user_path(@book.user) do %>
           <%= image_tag(@book.user.profile_image.variant(resize_to_limit: [100, 100])) %>
           <% end %>
             <% else %>
                <%= image_tag 'no_image', size: "100x100" %>
       <% end %>
            </td>
          </tr>
          <tr>
            <th>name</th>
            <td><%= @book.user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @book.user.introduction %></td>
          </tr>
        </tbody>
      </table>

<div class="row">
  <div class="col-12">
   <% if @book.user == current_user %>
  <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
    <span class="icon-wrapper">
      <i class="fas fa-user-cog" aria-hidden="true"></i>
    </span>
  <% end %>
<% else %>
  <%= link_to edit_user_path(@book.user), class: "btn btn-outline-secondary btn-block" do %>
    <span class="icon-wrapper">
      <i class="fas fa-user-cog" aria-hidden="true"></i>
    </span>
  <% end %>
<% end %>

  </div>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: Book.new do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control" %>
  <p class="mt-3">Opinion</p>
  <%= f.text_area :body, class: "form-control" %>
  <%= f.submit 'Create Book', class: "btn btn-success mt-3 " %>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
          <% if @book.user.profile_image.attached? %>
            <%= link_to user_path(@book.user) do %>
              <%= image_tag(@book.user.profile_image.variant(resize_to_limit: [100, 100])) %>
                <% end %>
                  <% end %>
        <p><%= link_to @book.user.name, user_path(@book.user) %></p>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td> <%= @book.body %></td>
          <td><% if current_user == @book.user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
                  <% end %>
          </td>
          <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
                <% end %>
          </td>
      </tr>
     </tbody>
 </table>
</div>
</div>
   </div>
 </main>
</body>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
<h1 class="px-3 mx-auto">
  Welcome to
  <i class="fas fa-book" aria-hidden="true">
  </i>
  <strong>Bookers</strong>
  !
 </h1>
  </div>
</div>

app/views/homes/top.html.erb
<body>
<% flash.each do |message_type, message| %>
<%= content_tag :div, message, class: message_type %>
<% end %>
<main>
  <div class="container">
   <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
 <h1>
  welcome to
  <i class="fas fa-book" aria-hidden="true">
  </i>
  <strong>Bookers</strong>
  !!
 </h1>
<p>
 In
  <i class="fas fa-book" aria-hidden="true">
  </i>
 <strong>Bookers</strong>
  ,
</p>
<p>
  you can share and exchange your opinions , inpressions , and emotions
</p>
<p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
    <div class="row">
  <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block sign_in" %>
　　</div>
    <div class="row">
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
    </div>
      </div>
    </div>
  </div>
</div>
</main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/4d5edc858e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

<div class="navbar-collapse collapse show" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
          <i class="fas fa-home"></i> Home
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to  users_path, class: "nav-link text-light" do %>
         <i class="fas fa-users"></i> Users
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class: "nav-link text-light" do %>
         <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
         <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>

    <% else %>
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link text-light" do %>
         <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li class="nav-item">
    <%= link_to about_path, class: "nav-link text-light" do %>
    <i class="fas fa-link"></i> About
    <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
         <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class: "nav-link text-light" do %>
         <i class="fas fa-sign-in-alt"></i> Log in
        <% end %>
      </li>

    <% end %>
  </ul>
</div>
</header>
<%= yield %>
</body>

<footer>
    <div class="container mt-5">
     <div class="row">
      <div class="mx-auto">
     <p>CopyRight Infratop.inc</p>
      </div>
     </div>
    </div>
   </footer>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
        <h2>User info</h2>
  <% if @user.errors.any? %>
  <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
      <%= form_with(model: @user, url: user_path(@user), method: :patch) do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "名前" %>
        </div>
        <div class="form-group">
          <%= f.label :profile_image, "Image" %>
          <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<body>
  <main>
    <div>
  <%= flash[:notice] %>
</div>

  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mb-0 border-bottom-0">User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
       <% if @user.profile_image.attached? %>
         <%= image_tag(@user.profile_image.variant(resize_to_limit: [100, 100])) %>
           <% else %>
            <%= image_tag 'no_image', size: "100x100" %>
        <% end %>
            </td>
          </tr>
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>

<div class="row">
  <div class="col-12">
    <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog" aria-hidden="true"></i>
    <% end %>
  </div>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book, url: books_path do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control", name: "book[title]" %>
  <p class="mt-3">Opinion</p>
  <%= f.text_area :body, class: "form-control", name: "book[body]" %>
  <%= f.submit 'Create Book', class: "btn btn-success mt-3 " %>
<% end %>


</div>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
  <% @users.each do |user| %>
  <tr>
    <td>
      <% if user.profile_image.attached? %>
        <%= image_tag(user.profile_image.variant(resize_to_limit: [100, 100])) %>
          <% else %>
            <%= image_tag 'no_image', size: "80x80" %>
      <% end %>
    </td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user) %></td>
  </tr>
<% end %>
</tbody>

  </table>
     </div>
    </div>
  </div>
 </main>
</body>

app/views/users/show.html.erb
<body>
  <main>
<div>
  <%= flash[:notice] %>
</div>

  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
             <% if @user.profile_image.attached? %>
                <%= image_tag(@user.profile_image.variant(resize_to_limit: [100, 100])) %>
                  <% else %>
                    <%= image_tag('no_image', size: "100x100") %>
            <% end %>
            </td>
          </tr>
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>

<div class="row">
  <div class="col-12">
    <% if @user != current_user %>
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog" aria-hidden="true"></i>
      <% end %>
        <% else %>
          <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog" aria-hidden="true"></i>
      <% end %>
    <% end %>

      <% if @user == current_user %>
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block", style: "display: none" do %>
          <i class="fas fa-user-cog" aria-hidden="true"></i>
        <% end %>
      <% end %>

  </div>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: @book, url: books_path do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class: "form-control", name: "book[title]" %>
  <p class="mt-3">Opinion</p>
  <%= f.text_area :body, class: "form-control", name: "book[body]" %>
  <%= f.submit 'Create Book', class: "btn btn-success mt-3 " %>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
  <tr>
    <td>
      <% if book.user.profile_image.attached? %>
        <%= link_to image_tag(book.user.profile_image.variant(resize_to_limit: [100, 100])) %>
      <% end %>
    </td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>

    </div>
  </div>
 </main>
</body>